apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: pi-spring-boot
          image: roohoo/chorewebsite:1.6
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 500Mi
              cpu: 1000m
            limits:
              memory: 1000Mi
              cpu: 3000m
